---
title: "DIY"
output:
  html_document:
    toc: true
    toc_float: true
---

Check out our [DIY tutorials and guidelines](https://davisnightmarket.github.io/diy) to get started with Night Market in your own community!!! 

# [how to legally night market](https://davisnightmarket.github.io/diy/legal) 

Learn all about the liability protections and the necessary permits you need to get started donating food!! 

# [how to build night market stuff ](https://davisnightmarket.github.io/diy/build) 

Learn how to re-furbish a used bike cart and make a dope LED-sign! 


# [how to do food recovery for night market](https://davisnightmarket.github.io/diy/food recovery) 

Step by step guide of the process of actually picking up and donating the recovered food

# [how to do organize a night market](https://davisnightmarket.github.io/diy/organize) 

Learn how to get a Night market started, from recruiting restaurants, businesses and volunteers to tips on mutual aid and non-hierarchical organization models 

# [how to build community at night market](https://davisnightmarket.github.io/diy/community) 

Or how to throw a party every night :) 


